# Generated by Django 4.2.6 on 2023-10-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_product_customuser_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
